
version: '3.7'
services:
  datadog-service:
    container_name: 'datadog-service'
    build: .
    depends_on:
      - 'distributor'
    ports:
      - '8080:8080'
    environment:
      - CONFIGURATION_SERVICE=http://configuration-service:8080
  distributor:
    image: 'keptn/distributor:0.8.3'
    container_name: 'keptn-distributor'
    ports:
      - '8080'
    environment:
      - PUBSUB_URL=nats://keptn-nats-cluster
      - PUBSUB_TOPIC=sh.keptn.>
      - PUBSUB_RECIPIENT=127.0.0.1