apiVersion: v1
kind: Service
metadata:
  name: jonathan
  namespace: keptn
  labels:
    app.kubernetes.io/name: jonathan
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: keptn
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: resource-service
    app.kubernetes.io/instance: keptn
