{{- if not .Values.splunkservice.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "splunk-service.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "splunk-service.labels" . | nindent 4 }}
type: Opaque
data:
SP_HOST: {{ required "A valid SP_HOST is required to connect to the Splunk API" toString .Values.splunkservice.spHost | b64enc | quote }}
SP_PORT: {{ required "A valid SP_PORT is required to connect to the Splunk API" (toString .Values.splunkservice.spPort) | b64enc | quote }}
SP_USERNAME: {{toString .Values.splunkservice.spUser | b64enc | quote }}
SP_PASSWORD: {{toString .Values.splunkservice.spPassword | b64enc | quote }}
SP_API_TOKEN: {{toString .Values.splunkservice.spApitoken | b64enc | quote }}
SP_SESSION_KEY: {{toString .Values.splunkservice.spSessionKey | b64enc | quote }}
{{- end -}}