{{- if .Values.splunkservice.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk-service.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "splunk-service.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: default
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30036
  selector:
    {{- include "splunk-service.selectorLabels" . | nindent 4 }}
  {{- end }}
