{{- if not .Values.splunkservice.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "splunk-service.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "splunk-service.labels" . | nindent 4 }}
type: Opaque
data:
  SP_API_TOKEN: {{ required "A valid SP_API_TOKEN is required to connect to the Splunk API" .Values.splunkservice.spApitoken | b64enc | quote }}
  SP_HOST: {{ required "A valid SP_HOST is required to connect to the Splunk API" .Values.splunkservice.spHost | b64enc | quote }}
  SP_PORT: {{ required "A valid SP_PORT is required to connect to the Splunk API" .Values.splunkservice.spPort | b64enc | quote }}
{{- end -}}