{{- if not .Values.datadogservice.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datadog-service.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "datadog-service.labels" . | nindent 4 }}
type: Opaque
data:
  DD_API_KEY: {{ required "A valid DD_API_KEY is required to connect to the Datadog API" .Values.datadogservice.ddApikey | b64enc | quote }}
  DD_APP_KEY: {{ required "A valid DD_APP_KEY is required to connect to the Datadog API" .Values.datadogservice.ddAppKey | b64enc | quote }}
  DD_SITE: {{ required "A valid DD_SITE is required to connect to the Datadog API" .Values.datadogservice.ddSite | b64enc | quote }}

{{- end -}}