{{- if .Values.splunkservice.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk-service.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "splunk-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
  selector:
    {{- include "splunk-service.selectorLabels" . | nindent 4 }}
  {{- end }}