# Sets namespace for all the templates (set to chart release's namespace if empty)
namespace: keptn
splunkservice:
  logLevel: info
  # Set to SP_API_TOKEN in the chart's Secret
  spApitoken: "gezg899255ddkjgdf"
  spHost: "localhost:8089"
  # Make splunk-service wait for 120 seconds before querying the Splunk API
  # so that the API reflects correct metric data
  sleepBeforeAPIInSeconds: "120"
  # Secret containing splunk's SP_API_TOKEN
  #  SP_API_TOKEN and SP_HOST (token names should be an exact match)
  existingSecret: "" # If you want to use existing Secret in the cluster
  KeptnEndpoint: "localhost:8089"
  image:
    repository: kuro08/splunk-service # Container Image Name
    pullPolicy: IfNotPresent                   # Kubernetes Image Pull Policy
    tag: latest                                # Container Tag
  service:
    enabled: true                              # Creates a Kubernetes Service for the splunk-service

distributor:
  stageFilter: ""                            # Sets the stage this helm service belongs to
  serviceFilter: ""                          # Sets the service this helm service belongs to
  projectFilter: ""                          # Sets the project this helm service belongs to
  image:
    repository: ghcr.io/keptn/distributor  # Container Image Name
    pullPolicy: IfNotPresent                 # Kubernetes Image Pull Policy
    tag: "1.0.0"                                  # Container Tag

remoteControlPlane:
  enabled: false                             # Enables remote execution plane mode
  api:
    protocol: "http"                        # Used Protocol (http, https)
    hostname: ""                            # Hostname of the control plane cluster (and Port)
    apiValidateTls: true                     # Defines if the control plane certificate should be validated
    token: ""                                # Keptn API Token

imagePullSecrets: []                         # Secrets to use for container registry credentials

serviceAccount:
  create: true                               # Enables the service account creation
  annotations: {}                            # Annotations to add to the service account
  name: ""                                   # The name of the service account to use.

podAnnotations: {}                           # Annotations to add to the created pods

podSecurityContext: {}                       # Set the pod security context (e.g. fsGroups)
  # fsGroup: 2000

securityContext: {}                          # Set the security context (e.g. runAsUser)
#  readOnlyRootFilesystem: true
#  runAsNonRoot: true
#  runAsUser: 1000

resources:                                 # Resource limits and requests
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
     cpu: 100m
     memory: 128Mi

nodeSelector: {}                                # Node selector configuration

tolerations: []                                 # Tolerations for the pods

affinity: {}                                    # Affinity rules
