name: Build and deploy splunk service to docker Hub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Set up Python version
      #   uses: actions/setup-python@v3.0.0
      #   with:
      #     python-version: ${{ env.PYTHON_VERSION }}
      #     cache: 'pip'

      # - name: Create and start virtual environment
      #   run: |
      #     python -m venv venv
      #     source venv/bin/activate

      # - name: Install dependencies
      #   run: pip install -r requirements.txt

      # - name: Upload artifact for deployment jobs
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: python-app
      #     path: |
      #       .
      #       !venv/
       
      - name: Build and Push splunk service Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: kuro08/splunk-service
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and Push splunk entreprise Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: kuro08/splunk-entreprise
          dockerfile: splunkDeploy/Dockerfile
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
          
